// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdvfjkdsqerhaoveursw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkdmZqa2RzcWVyaGFvdmV1cnN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NTIxMjQsImV4cCI6MjA2OTQyODEyNH0.CQxsbESgWvS7HFXVvcCckOKhOQHz427EtVXdrATjPM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});